---
counterActIP: <ip-address>  # Your EM / CT IP
Web-API:                    # WebAPI Settings
    User: <username>        # Your Username of WebAPI
    Password: <password>    # Your Password of WebAPI
DEX-Web-Serivces:           # DEX Web Services Settings
    User: <name>@<username> # Your User of DEX Account in format: <name>@<username>
    Password: <password>    # Your Password of DEX Account
